# Generated by Django 5.2.5 on 2025-08-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="failed_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
