# Generated by Django 5.2.5 on 2025-08-27 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام امکانات")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
            ],
            options={
                "verbose_name": "امکانات",
                "verbose_name_plural": "امکانات",
            },
        ),
        migrations.CreateModel(
            name="Mosque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام مسجد")),
                ("province", models.CharField(max_length=100, verbose_name="استان")),
                ("city", models.CharField(max_length=100, verbose_name="شهر")),
                ("address", models.TextField(verbose_name="آدرس دقیق")),
                ("latitude", models.FloatField(verbose_name="عرض جغرافیایی")),
                ("longitude", models.FloatField(verbose_name="طول جغرافیایی")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
            ],
            options={
                "verbose_name": "مسجد",
                "verbose_name_plural": "مساجد",
            },
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام سالن")),
                ("capacity", models.PositiveIntegerField(verbose_name="ظرفیت")),
                (
                    "price_per_hour",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="قیمت به ازای هر ساعت",
                    ),
                ),
                (
                    "facilities",
                    models.ManyToManyField(
                        blank=True, to="mosque.facility", verbose_name="امکانات"
                    ),
                ),
                (
                    "mosque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="halls",
                        to="mosque.mosque",
                        verbose_name="مسجد",
                    ),
                ),
            ],
            options={
                "verbose_name": "سالن",
                "verbose_name_plural": "سالن\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/", verbose_name="تصویر")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="توضیحات تصویر",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="mosque.hall",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "mosque",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="mosque.mosque",
                        verbose_name="مسجد",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر",
                "verbose_name_plural": "تصاویر",
            },
        ),
    ]
