# Generated by Django 5.2.5 on 2025-08-27 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0001_initial"),
        ("mosque", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mosque",
            name="province",
        ),
        migrations.AlterField(
            model_name="mosque",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="cities.city",
                verbose_name="شهر",
            ),
        ),
    ]
