# Generated by Django 5.2.5 on 2025-08-27 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservation", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddField(
            model_name="reservationservice",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation_services",
                to="reservation.reservation",
            ),
        ),
        migrations.AddField(
            model_name="reservationservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation_services",
                to="services.additionalservice",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                through="reservation.ReservationService",
                to="services.additionalservice",
                verbose_name="خدمات جانبی",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reservationservice",
            unique_together={("reservation", "service")},
        ),
    ]
