# Generated by Django 5.2.5 on 2025-08-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="authority",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="کد رهگیری پرداخت"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "در انتظار پرداخت"),
                    ("ACTIVE", "فعال"),
                    ("CANCELLED", "لغو شده"),
                    ("FAILED", "پرداخت ناموفق"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
    ]
